# Created with https://github.com/dart-lang/mono_repo
language: dart

####################
# Begin hand edits #
####################
sudo: required
addons:
  chrome: stable

env:
  - DART_VM_OPTIONS=--preview-dart-2

after_failure:
 - tool/report_failure.sh
##################
# End hand edits #
##################

jobs:
  include:
    - stage: e2e_test
      script: ./tool/travis.sh test_0
      env: PKG="_test"
      dart: be/raw/latest
    - stage: e2e_test
      script: ./tool/travis.sh test_1
      env: PKG="_test"
      dart: be/raw/latest
    - stage: e2e_test
      script: ./tool/travis.sh test_2
      env: PKG="_test"
      dart: be/raw/latest
    - stage: e2e_test
      script: ./tool/travis.sh test_3
      env: PKG="_test"
      dart: be/raw/latest
    - stage: e2e_test_cron
      script: ./tool/travis.sh test_4
      env: PKG="_test"
      dart: be/raw/latest
    - stage: e2e_test
      script: ./tool/travis.sh test_6
      env: PKG="build_runner"
      dart: be/raw/latest
    - stage: unit_test
      script: ./tool/travis.sh test_7
      env: PKG="build_web_compilers"
      dart: be/raw/latest

stages:
  - analyze_and_format
  - unit_test
  - e2e_test
  - name: e2e_test_cron
    if: type IN (api, cron)

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
